products = [
    {
        "_id":1,
        "productname":"Camera",
        "category":"Electronics",
        "price":5000
    },
    {
        "_id":1,
        "productname":"Laptop",
        "category":"Electronics",
        "price":5000
    },
    {
        "_id":1,
        "productname":"Mobile",
        "category":"Electronics",
        "price":5000
    }
]